approve_by_comment: true
approve_regex: ^Approved
author_approval: default
reject_regex: ^Rejected
reset_on_push: true
reset_on_reopen: true
reviewers:
  members:
  - rlee287
  name: owner
  required: 1
