language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy"
  - "pypy3"
cache: 
  pip: true
  directories: $HOME/.pylint.d
notifications:
  email: false
install:
  - pip install requests
  - pip install coverage
  - pip install pylint
script: 
  - bash .travis_scripts/run_travis.sh
after_success:
  - pip install codecov
  - coverage xml -i
  - python -c 'import sys;print(str(sys.version_info[0])+"."+str(sys.version_info[1]))' > version.txt
  - cat version.txt | xargs codecov --env
  - rm version.txt
  - cd ..; pylint -f colorized pyautoupdate; cd pyautoupdate
