language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy"
  - "pypy3"
notifications:
  email:
    on_success: change
    on_failure: change
install:
  - pip install requests
script: 
  - echo $PWD
  - touch pytestlog.log
  - py.test -v --result-log=pytestlog.log ./testing
  - cat pytestlog.log
