language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy"
  - "pypy3"
cache: 
  pip: true
  directories: $HOME/.pylint.d
notifications:
  email: false
install:
  - pip install requests
  - pip install pytest-cov
  - pip install pylint
script: 
  - py.test --cov-report xml ./testing
after_success:
  - . testing/scripts/lint_linux.sh
  - pip install codecov
  - PY_VERSION=python -c 'import sys;print(sys.version_info[0]+"."+sys.version_info[1])'
  - codecov --env $PY_VERSION
