language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy"
  - "pypy3"
cache: 
  pip: true
  directories: $HOME/.pylint.d
notifications:
  email: false
install:
  - pip install requests
  - pip install pytest-cov
  - pip install pylint
script: 
  - testing/scripts/run_linux.sh
after_success:
  - testing/scripts/lint_linux.sh
