language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy"
  - "pypy3"
notifications:
  email:
    on_success: change
    on_failure: change
install:
  - pip install requests
  - pip install pytest-cov
script: 
  - touch pytestlog.log
  - py.test -vlr --cov=py_autoupdate --cov-report=term --result-log=pytestlog.log ./testing
  - cat pytestlog.log
