language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
notifications:
  email:
    on_success: change
    on_failure: change
install:
  - pip install requests
script: 
  - echo $PWD
  - touch pytestlog.log
  - py.test -v --result-log=pytestlog.log ./testing
  - cat pytestlog.log
