language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy"
  - "pypy3"
cache: pip
notifications:
  email:
    on_success: change
    on_failure: change
install:
  - pip install requests
  - pip install pytest-cov
script: 
  - . testing/scripts/run_linux.sh
